### ISSUE TITLE
没有发现Release的捏~

### ISSUE THREAD

**Issue by cute-omega** [123Duo3/XDNMB#3]
![QQ截图20230718155042](https://github.com/123Duo3/XDNMB/assets/92797441/d613d612-8e1a-4ae4-9f8b-e2986cdbf79e)
![QQ截图20230718155207](https://github.com/123Duo3/XDNMB/assets/92797441/f390b04d-1f20-4350-b41e-98bf5550e6db)
So？

**Comment by 123Duo3** [comment]
因为现在还有很多功能没有完善，所以还没有任何 release（
等不及的话您可以自己编译一个，看看现在的进度。或者继续等下去，功能做得差不多了会第一时间 release。

**Comment by Konyaco** [comment]
> 因为现在还有很多功能没有完善，所以还没有任何 release（ 等不及的话您可以自己编译一个，看看现在的进度。或者继续等下去，功能做得差不多了会第一时间 release。

一年内能release吗

**Comment by kevinluo6191** [comment]
嗯。。。2025了

**Comment by cute-omega** [comment]
> 因为现在还有很多功能没有完善，所以还没有任何 release（ 等不及的话您可以自己编译一个，看看现在的进度。或者继续等下去，功能做得差不多了会第一时间 release。

I started this issue just because I don't know how to compile it.
And I don't know why it was closed.
(I'm not using Chinese just because my Chinese IME is unavailable and I can't input Chinese)
